### ISSUE TITLE
Unhandled 'error' event on launch

### ISSUE THREAD

**Issue by gnestor** [n-riesco/jp-babel#1]
When I run `jp-babel` I get the following error. The '/usr/local/lib/node_modules/jp-babel/' directory exists, but there is obviously no 'images' subdirectory...not sure why it's looking one...

```
$ jp-babel
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/jp-babel/images/logo-32x32.png'
    at Error (native)
```

**Comment by n-riesco** [comment]
Sorry about that. It should work now.

**Comment by gnestor** [comment]
Thanks @n-riesco. 1 more thing... I get the following error when I try to run a cell in a notebook: 

```
Error: Couldn't find preset "es2015"
    at OptionManager.mergePresets (/usr/local/lib/node_modules/jp-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:310:17)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/jp-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:12)
    at OptionManager.init (/usr/local/lib/node_modules/jp-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:10)
    at File.initOptions (/usr/local/lib/node_modules/jp-babel/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/usr/local/lib/node_modules/jp-babel/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/usr/local/lib/node_modules/jp-babel/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/usr/local/lib/node_modules/jp-babel/lib/nel.js:57:12)
    at Session._runNow (/usr/local/lib/node_modules/jp-babel/lib/nel.js:337:32)
    at Session.run (/usr/local/lib/node_modules/jp-babel/lib/nel.js:315:14)
    at Kernel.execute_request (/usr/local/lib/node_modules/jp-babel/lib/handlers_v5.js:120:18)
```

I did a little Googling to see if others were having this issue with the Babel 6 upgrade but couldn't figure it out.

**Comment by gnestor** [comment]
I installed with Node 5.0 and it was an issue with NPM 3.x (https://github.com/npm/npm/blob/master/CHANGELOG.md#v300-2015-06-25). I installed again with Node 4.1.2 and it worked.

**Comment by n-riesco** [comment]
I've opened issue #2 to track the `Error: Couldn't find preset "es2015"` bug.
